# Cloud Run Job template for Producer execution (Pub/Sub-only)
#
# Provisioned by CI and then triggered by the Jobs service via
# projects.locations.jobs.run with minimal env overrides.
#
# Placeholders replaced in CI before applying:
# - __JOB_NAME__          -> repo var PRODUCER_CLOUD_RUN_JOB_NAME (e.g., producer-bridge)
# - __SERVICE_ACCOUNT__   -> vars.PRODUCER_JOB_SA_EMAIL or fallback CLOUD_RUN_RUNTIME_SA
# - __PRODUCER_IMAGE__    -> built image URI from CI (steps.producer_image)
# - __TOPIC__             -> shared Pub/Sub topic name (stable per env)
#
# Runtime defaults expected by jobs/producer:
# - Pub/Sub-only transport when PUBSUB_ENABLE=1
# - SUBSCRIPTION and ENC_KEY_B64 are typically provided per-run by the orchestrator
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: __JOB_NAME__
spec:
  template:
    # ExecutionTemplate
    spec:
      taskCount: 1
      parallelism: 1
      template:
        # TaskTemplate
        spec:
          serviceAccountName: __SERVICE_ACCOUNT__
          # NOTE: gcloud's canonical YAML uses a string here (e.g. '600')
          timeoutSeconds: "3600"
          containers:
          - image: __PRODUCER_IMAGE__
            env:
            - name: NODE_ENV
              value: production
            - name: PUBSUB_ENABLE
              value: "1"
            - name: TOPIC
              value: "__TOPIC__"
            # Per-run values; the Jobs runner typically overrides these at run time
            - name: SUBSCRIPTION
              value: ""
            - name: ENC_KEY_B64
              value: ""
